В этом задании вам предстоит поработать с публичным API и базой данных PostgreSQL.

#### Работа с API

- Изучить документацию [API OF ICE AND FIRE](https://github.com/joakimskoog/AnApiOfIceAndFire/wiki)
- Получить информацию обо всех книгах и сохранить в pd.DataFrame - **1 балл**

hint: используйте метод `requests.get()`
- Получить информацию обо всех домах Вестероса (Houses)  и сохранить в pd.DataFrame - **1 балл**

hint: используйте метод `requests.get()`
- Получить информацию обо всех домах Вестероса, у которых есть девиз,  и сохранить в pd.DataFrame - **2 балла**

hint: используйте метод `requests.get()`, используйте параметр `words` для фильтрации

#### Работа с БД

- Установить библиотеку psycopg2 (`pip install psycopg2-binary`)
- Подключиться к [БД](https://rnacentral.org/help/public-database) - **1 балл**

hint: используйте для подключения параметры `Hostname, Database, User, Password`, указанные на странице БД, и метод `psycopg2.connect()`
- Получите 10 строк из таблицы `rnc_database` - **2 балла**

hint: используйте методы `conn.cursor()`, `cursor.execute()`, `cursor.fetchall()`. В SQL-запросе не забудьте использовать `LIMIT 10`
- Сохраните полученные данные в pd.DataFrame - **1 балл**
- Получите значения столбцов `display_name`, `num_sequences`, `num_organisms`, , `url` для 10 строк из таблицы `rnc_database` - **2 балла**

hint: используйте методы `conn.cursor()`, `cursor.execute()`, `cursor.fetchall()`. В SQL-запросе не забудьте использовать `LIMIT 10` и указать нужные вам столбцы

In [1]:
import requests
import pandas as pd

Обратимся к апи по данным из библиотеки

In [2]:
api_base_url = 'https://www.anapioficeandfire.com/api'

Получи информацию о всех книгах в формате json

In [3]:
response = requests.get(
    f'{api_base_url}/books'
)
book_list = response.json()

Создадим датафрейм и отобразим полученные данные

In [4]:
book_df = pd.DataFrame(book_list)
book_df.head()

,url,name,isbn,authors,numberOfPages,publisher,country,mediaType,released,characters,povCharacters
0,https://www.anapioficeandfire.com/api/books/1,A Game of Thrones,978-0553103540,[George R. R. Martin],694,Bantam Books,United States,Hardcover,1996-08-01T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/books/2,A Clash of Kings,978-0553108033,[George R. R. Martin],768,Bantam Books,United States,Hardback,1999-02-02T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/books/3,A Storm of Swords,978-0553106633,[George R. R. Martin],992,Bantam Books,United States,Hardcover,2000-10-31T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/books/4,The Hedge Knight,978-0976401100,[George R. R. Martin],164,Dabel Brothers Publishing,United States,GraphicNovel,2005-03-09T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/books/5,A Feast for Crows,978-0553801507,[George R. R. Martin],784,Bantam Books,United Status,Hardcover,2005-11-08T00:00:00,[https://www.anapioficeandfire.com/api/charact...,[https://www.anapioficeandfire.com/api/charact...

Проделаем тоже самое для домов Вестероса

In [5]:
response = requests.get(f'{api_base_url}/houses')
houses_list = response.json()

In [6]:
houses_df = pd.DataFrame(houses_list)
houses_df.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/1,House Algood,The Westerlands,"A golden wreath, on a blue field with a gold b...",,[],[],,,https://www.anapioficeandfire.com/api/houses/229,,,,[],[],[]
1,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/3,House Amber,The North,,,[],[],,,,,,,[],[],[]
3,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
4,https://www.anapioficeandfire.com/api/houses/5,House Appleton of Appleton,The Reach,"Or, an apple tree eradicated proper fructed gu...",,[],[Appleton],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[]

Сделаем то же самое только поставим фильтр на дома у которых есть девиз

In [7]:
respose = requests.get(f'{api_base_url}/houses/')
whouses_list = response.json()

In [8]:
houses_with_words = [house for house in houses_list if house.get('words')]

In [9]:
houses_with_words = pd.DataFrame(houses_with_words)
houses_with_words.head()

,url,name,region,coatOfArms,words,titles,seats,currentLord,heir,overlord,founded,founder,diedOut,ancestralWeapons,cadetBranches,swornMembers
0,https://www.anapioficeandfire.com/api/houses/2,House Allyrion of Godsgrace,Dorne,"Gyronny Gules and Sable, a hand couped Or",No Foe May Pass,[],[Godsgrace],https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/285,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
1,https://www.anapioficeandfire.com/api/houses/4,House Ambrose,The Reach,"Or, semy of ants gules",Never Resting,[],[],https://www.anapioficeandfire.com/api/characte...,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...
2,https://www.anapioficeandfire.com/api/houses/7,House Arryn of the Eyrie,The Vale,A sky-blue falcon soaring against a white moon...,As High as Honor,"[King of Mountain and Vale (formerly), Lord of...","[The Eyrie (summer), Gates of the Moon (winter)]",https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/characte...,https://www.anapioficeandfire.com/api/houses/16,Coming of the Andals,https://www.anapioficeandfire.com/api/characte...,,[],[https://www.anapioficeandfire.com/api/houses/6],[https://www.anapioficeandfire.com/api/charact...
3,https://www.anapioficeandfire.com/api/houses/8,House Ashford of Ashford,The Reach,"Tenny, a sun in splendour beneath a chevron in...",Our Sun Shines Bright,[Lord of Ashford],[Ashford],,,https://www.anapioficeandfire.com/api/houses/398,,,,[],[],[https://www.anapioficeandfire.com/api/charact...

API
---

Установим библиотеку

In [10]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.10/dist-packages (2.9.10)

In [11]:
import psycopg2

Подключимся к БД

In [12]:
host = 'hh-pgsql-public.ebi.ac.uk'
port = 5432
database = 'pfmegrnargs'
user = 'reader'
password = 'NWDMCE5xdipIjRrp'

Используем команду try и подключимся к БД

In [13]:
try:
    conn = psycopg2.connect(dbname=database, user=user, password=password, host=host)
except:
    print('Can`t establish connection to database')

Воспользуемся командой conn.cursor() для взаимодействия с БД и написания SQL запросов и выберем 10 строк из БД

In [14]:
with conn.cursor() as cursor:
    cursor.execute('SELECT * FROM rna limit 10')
    rna_10 = cursor.fetchall()

Выведем первые 10 строк в формате датафрейма

In [15]:
rna_10_df = pd.DataFrame(rna_10)
rna_10_df.head()

,0,1,2,3,4,5,6,7,8
0,10260232,URS00009C8F08,2016-12-07 06:53:51,RNACEN,DC0F20C63CA0AB97,1395,ATCATGGCTCAGGACGAACGCTGGCGGCGTGCCTAATACATGCAAG...,None,c4e10434a4b802987ab6d0895666c5f4
1,10260236,URS00009C8F0C,2016-12-07 06:53:51,RNACEN,07655CF7697D860B,753,GAGCGGCGGACGGGTGAGTAACACGTGGGCAACCTGCCTGTAAGAC...,None,c4e12e52b49592ead615a752c738b236
2,10260627,URS00009C9093,2016-12-07 06:53:51,RNACEN,625E38D9A241156D,1520,AGAGTTTGATCCTGGCTCAGAACGAACGCTGGCGGCGTGGATTAGG...,None,c5035ac45cf225b4ffb49a7bcba06898
3,10260628,URS00009C9094,2016-12-07 06:53:51,RNACEN,A60AF42782EA6668,449,ATAAACGCTGGCGGCGTGCTTCAGGCATGCAAGTCGAACGCCCCGA...,None,117c271f87a6341d11a15d0b42c6c365
4,10260630,URS00009C9096,2016-12-07 06:53:51,RNACEN,1F81D04E37A34D37,161,ACCCACATTGTACAGTGGATCACTTGGCTCGTAGGTCGATGAAGAA...,None,b162c87a3a1f2273f42d01438e34dfb4

Проделаем то же для определенных столбцов для 10 строк из таблицы

In [16]:
with conn.cursor() as cursor:
    cursor.execute('SELECT display_name, num_sequences, num_organisms, url FROM rnc_database LIMIT  10')
    rna_col = cursor.fetchall()

In [17]:
rna_col_df = pd.DataFrame(rna_col)
rna_col_df

,0,1,2,3
0,ENA,12086180,814855,https://www.ebi.ac.uk/ena/browser/
1,VEGA,0,0,http://vega.sanger.ac.uk/
2,GENCODE,47677,2,http://gencodegenes.org/
3,MGnify,135924,1929,None
4,GeneCards,517673,1,https://www.genecards.org/
5,RDP,4779,2487,http://rdp.cme.msu.edu/
6,LNCipedia,126876,1,http://www.lncipedia.org/
7,snoRNA Database,680,10,http://lowelab.ucsc.edu/snoRNAdb/
8,Rfam,1879595,14792,http://rfam.org
9,piRBase,200827,17,http://www.regulatoryrna.org/database/piRNA/